import {useEffect,useState} from "react";
import {createMaterialRequest,deliverMaterialRequest,getDemands,getInventory,getMaterialRequests,getMaterialRequestSummary,separateMaterialRequest,transitionMaterialRequest} from "../api/kynkaApi";
const LABEL={requested:"Solicitado",approved:"Aprovado",separating:"Em separacao",shortage:"Sem estoque",ready:"Pronto",delivered:"Entregue",cancelled:"Cancelado"};
const EMPTY={demand_id:"",requester_name:"",priority:"normal",notes:"",items:[{material_code:"",quantity:""}]};
export default function MaterialRequestsPanel(){
 const [requests,setRequests]=useState([]),[summary,setSummary]=useState({}),[demands,setDemands]=useState([]),[materials,setMaterials]=useState([]),[filter,setFilter]=useState(""),[form,setForm]=useState(EMPTY),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [r,s,d,m]=await Promise.all([getMaterialRequests(filter||null),getMaterialRequestSummary(),getDemands(),getInventory()]);setRequests(r);setSummary(s);setDemands(d);setMaterials(m)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[filter]);
 function item(i,k,v){setForm(c=>({...c,items:c.items.map((x,n)=>n===i?{...x,[k]:v}:x)}))}
 async function submit(e){e.preventDefault();setSaving(true);setError("");setSuccess("");try{await createMaterialRequest({...form,demand_id:Number(form.demand_id),items:form.items.map(x=>({material_code:x.material_code,quantity:Number(x.quantity)}))});setForm(EMPTY);setSuccess("Solicitacao enviada ao estoque.");await load()}catch(x){setError(x.message)}finally{setSaving(false)}}
 async function act(fn,msg){setError("");setSuccess("");try{await fn();setSuccess(msg);await load()}catch(x){setError(x.message)}}
 return <section className="material-requests-page"><div className="material-requests-header"><span className="page-eyebrow">Operacao</span><h2>Solicitacoes de Material</h2><p>Pedidos das obras diretamente para o encarregado de estoque.</p></div>{error&&<div className="mr-alert error">{error}</div>}{success&&<div className="mr-alert success">{success}</div>}
 <div className="mr-stats"><div><strong>{summary.total||0}</strong><span>Total</span></div><div><strong>{summary.requested||0}</strong><span>Novos</span></div><div><strong>{summary.ready||0}</strong><span>Prontos</span></div><div><strong>{summary.shortage||0}</strong><span>Com falta</span></div></div>
 <div className="mr-layout"><form className="mr-card mr-form" onSubmit={submit}><h3>Novo pedido da obra</h3><label>Obra / projeto<select required value={form.demand_id} onChange={e=>setForm({...form,demand_id:e.target.value})}><option value="">Selecione...</option>{demands.map(d=><option key={d.id} value={d.id}>{d.code} - {d.name}</option>)}</select></label><div className="mr-row"><label>Funcionario<input required value={form.requester_name} onChange={e=>setForm({...form,requester_name:e.target.value})}/></label><label>Prioridade<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div>
 <div>{form.items.map((x,i)=><div className="mr-item" key={i}><select required value={x.material_code} onChange={e=>item(i,"material_code",e.target.value)}><option value="">Material...</option>{materials.map(m=><option key={m.code} value={m.code}>{m.code} - {m.name} ({m.quantity} {m.unit})</option>)}</select><input required type="number" min="0.0001" step="any" placeholder="Qtd." value={x.quantity} onChange={e=>item(i,"quantity",e.target.value)}/>{form.items.length>1&&<button type="button" onClick={()=>setForm(c=>({...c,items:c.items.filter((_,n)=>n!==i)}))}>x</button>}</div>)}</div><button type="button" className="secondary-button" onClick={()=>setForm(c=>({...c,items:[...c.items,{material_code:"",quantity:""}]}))}>+ Material</button><label>Observacoes<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary-button" disabled={saving}>{saving?"Enviando...":"Enviar solicitacao"}</button></form>
 <div className="mr-card"><div className="mr-list-head"><h3>Fila do estoque</h3><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{Object.entries(LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="mr-list">{requests.map(r=><article className="mr-request" key={r.id}><div className="mr-request-top"><div><strong>{r.code}</strong><span>{r.demand_code} - {r.demand_name}</span></div><span className={`mr-status ${r.status}`}>{LABEL[r.status]||r.status}</span></div><div className="mr-meta"><span>Solicitante: {r.requester_name}</span><span>Prioridade: {r.priority}</span></div><div className="mr-request-items">{r.items.map(i=><div key={i.id}><span>{i.material_code} - {i.material_name}</span><strong>{i.quantity_requested} {i.unit}</strong></div>)}</div><div className="mr-actions">{r.status==="requested"&&<button onClick={()=>act(()=>transitionMaterialRequest(r.id,"approved","Encarregado"),`${r.code} aprovada.`)}>Aprovar</button>}{["approved","shortage"].includes(r.status)&&<button onClick={()=>act(()=>separateMaterialRequest(r.id,"Encarregado"),`${r.code} processada.`)}>Separar</button>}{r.status==="ready"&&<button onClick={()=>act(()=>deliverMaterialRequest(r.id,"Encarregado"),`${r.code} entregue.`)}>Entregar</button>}{!["delivered","cancelled"].includes(r.status)&&<button className="danger" onClick={()=>act(()=>transitionMaterialRequest(r.id,"cancelled","Encarregado"),`${r.code} cancelada.`)}>Cancelar</button>}</div></article>)}</div></div></div></section>
}
